name: Lint ARM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package-group: [".", "experimental"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Bootstrap
        working-directory: ${{ matrix.package-group }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          arm64v8/ubuntu:latest \
          bash -exc 'apt-get update && apt-get -y install curl wget sudo git && \
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && \
          sudo apt-get install -y nodejs && \
          npm install --ignore-scripts && \
          npx lerna bootstrap --no-ci --hoist --nohoist='zone.js''
      - name: Lint
        working-directory: ${{ matrix.package-group }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          arm64v8/ubuntu:latest \
          bash -exc 'apt-get update && apt-get -y install curl wget sudo git && \
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && \
          sudo apt-get install -y nodejs && \
          npm run lint && \
          npm run lint:examples'
      - name: Lint doc files
        if: ${{ matrix.package-group == '.' }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          arm64v8/ubuntu:latest \
          bash -exc 'apt-get update && apt-get -y install curl wget sudo git && \
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && \
          sudo apt-get install -y nodejs && \
          npm run compile && \
          NODE_OPTIONS=--max-old-space-size=4096 npm run docs && \
          npm run docs:test'
